### ISSUE TITLE
No location services request

### ISSUE THREAD

**Issue by djcopley** [xYello/ThePost#4]
Application never prompts user to allow location services. Perhaps this only happens when user is unauthenticated like myself?

**Comment by SirArkimedes** [comment]
Ah, yes. I go ahead and cancel the location search if the device is not signed in. It will do a regular search without any location data.

Here is where I am getting this from:
https://github.com/xYello/ThePost/blob/2b9b44d7340b6cbdfd791a963bb6cc2af7b2dacf/The%20Wave/Models/Filter.swift#L76-L80

**Comment by djcopley** [comment]
Ah very well.
